// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sock_message.proto
// Protobuf Java Version: 4.32.1

package com.qtodo.socket.proto;

@com.google.protobuf.Generated
public final class SockMessage extends com.google.protobuf.GeneratedFile {
  private SockMessage() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 1,
      /* suffix= */ "",
      SockMessage.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MessageProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string type = 1;</code>
     * @return The type.
     */
    java.lang.String getType();
    /**
     * <code>string type = 1;</code>
     * @return The bytes for type.
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <code>string message = 2;</code>
     * @return The message.
     */
    java.lang.String getMessage();
    /**
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
        getMessageBytes();

    /**
     * <code>string schema = 3;</code>
     * @return The schema.
     */
    java.lang.String getSchema();
    /**
     * <code>string schema = 3;</code>
     * @return The bytes for schema.
     */
    com.google.protobuf.ByteString
        getSchemaBytes();

    /**
     * <code>repeated .UserProto users = 4;</code>
     */
    java.util.List<com.qtodo.socket.proto.User.UserProto> 
        getUsersList();
    /**
     * <code>repeated .UserProto users = 4;</code>
     */
    com.qtodo.socket.proto.User.UserProto getUsers(int index);
    /**
     * <code>repeated .UserProto users = 4;</code>
     */
    int getUsersCount();
    /**
     * <code>repeated .UserProto users = 4;</code>
     */
    java.util.List<? extends com.qtodo.socket.proto.User.UserProtoOrBuilder> 
        getUsersOrBuilderList();
    /**
     * <code>repeated .UserProto users = 4;</code>
     */
    com.qtodo.socket.proto.User.UserProtoOrBuilder getUsersOrBuilder(
        int index);

    /**
     * <code>repeated string user_groups = 5;</code>
     * @return A list containing the userGroups.
     */
    java.util.List<java.lang.String>
        getUserGroupsList();
    /**
     * <code>repeated string user_groups = 5;</code>
     * @return The count of userGroups.
     */
    int getUserGroupsCount();
    /**
     * <code>repeated string user_groups = 5;</code>
     * @param index The index of the element to return.
     * @return The userGroups at the given index.
     */
    java.lang.String getUserGroups(int index);
    /**
     * <code>repeated string user_groups = 5;</code>
     * @param index The index of the value to return.
     * @return The bytes of the userGroups at the given index.
     */
    com.google.protobuf.ByteString
        getUserGroupsBytes(int index);

    /**
     * <code>repeated .TodoItemProto items = 6;</code>
     */
    java.util.List<com.qtodo.socket.proto.TodoItem.TodoItemProto> 
        getItemsList();
    /**
     * <code>repeated .TodoItemProto items = 6;</code>
     */
    com.qtodo.socket.proto.TodoItem.TodoItemProto getItems(int index);
    /**
     * <code>repeated .TodoItemProto items = 6;</code>
     */
    int getItemsCount();
    /**
     * <code>repeated .TodoItemProto items = 6;</code>
     */
    java.util.List<? extends com.qtodo.socket.proto.TodoItem.TodoItemProtoOrBuilder> 
        getItemsOrBuilderList();
    /**
     * <code>repeated .TodoItemProto items = 6;</code>
     */
    com.qtodo.socket.proto.TodoItem.TodoItemProtoOrBuilder getItemsOrBuilder(
        int index);

    /**
     * <code>repeated .TagProto tags = 7;</code>
     */
    java.util.List<com.qtodo.socket.proto.TodoItem.TagProto> 
        getTagsList();
    /**
     * <code>repeated .TagProto tags = 7;</code>
     */
    com.qtodo.socket.proto.TodoItem.TagProto getTags(int index);
    /**
     * <code>repeated .TagProto tags = 7;</code>
     */
    int getTagsCount();
    /**
     * <code>repeated .TagProto tags = 7;</code>
     */
    java.util.List<? extends com.qtodo.socket.proto.TodoItem.TagProtoOrBuilder> 
        getTagsOrBuilderList();
    /**
     * <code>repeated .TagProto tags = 7;</code>
     */
    com.qtodo.socket.proto.TodoItem.TagProtoOrBuilder getTagsOrBuilder(
        int index);

    /**
     * <code>bytes raw_data = 8;</code>
     * @return The rawData.
     */
    com.google.protobuf.ByteString getRawData();

    /**
     * <code>.google.protobuf.Timestamp created_at = 9;</code>
     * @return Whether the createdAt field is set.
     */
    boolean hasCreatedAt();
    /**
     * <code>.google.protobuf.Timestamp created_at = 9;</code>
     * @return The createdAt.
     */
    com.google.protobuf.Timestamp getCreatedAt();
    /**
     * <code>.google.protobuf.Timestamp created_at = 9;</code>
     */
    com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder();
  }
  /**
   * Protobuf type {@code MessageProto}
   */
  public static final class MessageProto extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:MessageProto)
      MessageProtoOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 32,
        /* patch= */ 1,
        /* suffix= */ "",
        MessageProto.class.getName());
    }
    // Use MessageProto.newBuilder() to construct.
    private MessageProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private MessageProto() {
      type_ = "";
      message_ = "";
      schema_ = "";
      users_ = java.util.Collections.emptyList();
      userGroups_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      items_ = java.util.Collections.emptyList();
      tags_ = java.util.Collections.emptyList();
      rawData_ = com.google.protobuf.ByteString.EMPTY;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.qtodo.socket.proto.SockMessage.internal_static_MessageProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.qtodo.socket.proto.SockMessage.internal_static_MessageProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.qtodo.socket.proto.SockMessage.MessageProto.class, com.qtodo.socket.proto.SockMessage.MessageProto.Builder.class);
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object type_ = "";
    /**
     * <code>string type = 1;</code>
     * @return The type.
     */
    @java.lang.Override
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      }
    }
    /**
     * <code>string type = 1;</code>
     * @return The bytes for type.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object message_ = "";
    /**
     * <code>string message = 2;</code>
     * @return The message.
     */
    @java.lang.Override
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SCHEMA_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object schema_ = "";
    /**
     * <code>string schema = 3;</code>
     * @return The schema.
     */
    @java.lang.Override
    public java.lang.String getSchema() {
      java.lang.Object ref = schema_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        schema_ = s;
        return s;
      }
    }
    /**
     * <code>string schema = 3;</code>
     * @return The bytes for schema.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSchemaBytes() {
      java.lang.Object ref = schema_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        schema_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERS_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private java.util.List<com.qtodo.socket.proto.User.UserProto> users_;
    /**
     * <code>repeated .UserProto users = 4;</code>
     */
    @java.lang.Override
    public java.util.List<com.qtodo.socket.proto.User.UserProto> getUsersList() {
      return users_;
    }
    /**
     * <code>repeated .UserProto users = 4;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.qtodo.socket.proto.User.UserProtoOrBuilder> 
        getUsersOrBuilderList() {
      return users_;
    }
    /**
     * <code>repeated .UserProto users = 4;</code>
     */
    @java.lang.Override
    public int getUsersCount() {
      return users_.size();
    }
    /**
     * <code>repeated .UserProto users = 4;</code>
     */
    @java.lang.Override
    public com.qtodo.socket.proto.User.UserProto getUsers(int index) {
      return users_.get(index);
    }
    /**
     * <code>repeated .UserProto users = 4;</code>
     */
    @java.lang.Override
    public com.qtodo.socket.proto.User.UserProtoOrBuilder getUsersOrBuilder(
        int index) {
      return users_.get(index);
    }

    public static final int USER_GROUPS_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringArrayList userGroups_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    /**
     * <code>repeated string user_groups = 5;</code>
     * @return A list containing the userGroups.
     */
    public com.google.protobuf.ProtocolStringList
        getUserGroupsList() {
      return userGroups_;
    }
    /**
     * <code>repeated string user_groups = 5;</code>
     * @return The count of userGroups.
     */
    public int getUserGroupsCount() {
      return userGroups_.size();
    }
    /**
     * <code>repeated string user_groups = 5;</code>
     * @param index The index of the element to return.
     * @return The userGroups at the given index.
     */
    public java.lang.String getUserGroups(int index) {
      return userGroups_.get(index);
    }
    /**
     * <code>repeated string user_groups = 5;</code>
     * @param index The index of the value to return.
     * @return The bytes of the userGroups at the given index.
     */
    public com.google.protobuf.ByteString
        getUserGroupsBytes(int index) {
      return userGroups_.getByteString(index);
    }

    public static final int ITEMS_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private java.util.List<com.qtodo.socket.proto.TodoItem.TodoItemProto> items_;
    /**
     * <code>repeated .TodoItemProto items = 6;</code>
     */
    @java.lang.Override
    public java.util.List<com.qtodo.socket.proto.TodoItem.TodoItemProto> getItemsList() {
      return items_;
    }
    /**
     * <code>repeated .TodoItemProto items = 6;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.qtodo.socket.proto.TodoItem.TodoItemProtoOrBuilder> 
        getItemsOrBuilderList() {
      return items_;
    }
    /**
     * <code>repeated .TodoItemProto items = 6;</code>
     */
    @java.lang.Override
    public int getItemsCount() {
      return items_.size();
    }
    /**
     * <code>repeated .TodoItemProto items = 6;</code>
     */
    @java.lang.Override
    public com.qtodo.socket.proto.TodoItem.TodoItemProto getItems(int index) {
      return items_.get(index);
    }
    /**
     * <code>repeated .TodoItemProto items = 6;</code>
     */
    @java.lang.Override
    public com.qtodo.socket.proto.TodoItem.TodoItemProtoOrBuilder getItemsOrBuilder(
        int index) {
      return items_.get(index);
    }

    public static final int TAGS_FIELD_NUMBER = 7;
    @SuppressWarnings("serial")
    private java.util.List<com.qtodo.socket.proto.TodoItem.TagProto> tags_;
    /**
     * <code>repeated .TagProto tags = 7;</code>
     */
    @java.lang.Override
    public java.util.List<com.qtodo.socket.proto.TodoItem.TagProto> getTagsList() {
      return tags_;
    }
    /**
     * <code>repeated .TagProto tags = 7;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.qtodo.socket.proto.TodoItem.TagProtoOrBuilder> 
        getTagsOrBuilderList() {
      return tags_;
    }
    /**
     * <code>repeated .TagProto tags = 7;</code>
     */
    @java.lang.Override
    public int getTagsCount() {
      return tags_.size();
    }
    /**
     * <code>repeated .TagProto tags = 7;</code>
     */
    @java.lang.Override
    public com.qtodo.socket.proto.TodoItem.TagProto getTags(int index) {
      return tags_.get(index);
    }
    /**
     * <code>repeated .TagProto tags = 7;</code>
     */
    @java.lang.Override
    public com.qtodo.socket.proto.TodoItem.TagProtoOrBuilder getTagsOrBuilder(
        int index) {
      return tags_.get(index);
    }

    public static final int RAW_DATA_FIELD_NUMBER = 8;
    private com.google.protobuf.ByteString rawData_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes raw_data = 8;</code>
     * @return The rawData.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getRawData() {
      return rawData_;
    }

    public static final int CREATED_AT_FIELD_NUMBER = 9;
    private com.google.protobuf.Timestamp createdAt_;
    /**
     * <code>.google.protobuf.Timestamp created_at = 9;</code>
     * @return Whether the createdAt field is set.
     */
    @java.lang.Override
    public boolean hasCreatedAt() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 9;</code>
     * @return The createdAt.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getCreatedAt() {
      return createdAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 9;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder() {
      return createdAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(type_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, type_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(message_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, message_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(schema_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, schema_);
      }
      for (int i = 0; i < users_.size(); i++) {
        output.writeMessage(4, users_.get(i));
      }
      for (int i = 0; i < userGroups_.size(); i++) {
        com.google.protobuf.GeneratedMessage.writeString(output, 5, userGroups_.getRaw(i));
      }
      for (int i = 0; i < items_.size(); i++) {
        output.writeMessage(6, items_.get(i));
      }
      for (int i = 0; i < tags_.size(); i++) {
        output.writeMessage(7, tags_.get(i));
      }
      if (!rawData_.isEmpty()) {
        output.writeBytes(8, rawData_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(9, getCreatedAt());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(type_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, type_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(message_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, message_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(schema_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, schema_);
      }
      for (int i = 0; i < users_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, users_.get(i));
      }
      {
        int dataSize = 0;
        for (int i = 0; i < userGroups_.size(); i++) {
          dataSize += computeStringSizeNoTag(userGroups_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getUserGroupsList().size();
      }
      for (int i = 0; i < items_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, items_.get(i));
      }
      for (int i = 0; i < tags_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, tags_.get(i));
      }
      if (!rawData_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, rawData_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, getCreatedAt());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.qtodo.socket.proto.SockMessage.MessageProto)) {
        return super.equals(obj);
      }
      com.qtodo.socket.proto.SockMessage.MessageProto other = (com.qtodo.socket.proto.SockMessage.MessageProto) obj;

      if (!getType()
          .equals(other.getType())) return false;
      if (!getMessage()
          .equals(other.getMessage())) return false;
      if (!getSchema()
          .equals(other.getSchema())) return false;
      if (!getUsersList()
          .equals(other.getUsersList())) return false;
      if (!getUserGroupsList()
          .equals(other.getUserGroupsList())) return false;
      if (!getItemsList()
          .equals(other.getItemsList())) return false;
      if (!getTagsList()
          .equals(other.getTagsList())) return false;
      if (!getRawData()
          .equals(other.getRawData())) return false;
      if (hasCreatedAt() != other.hasCreatedAt()) return false;
      if (hasCreatedAt()) {
        if (!getCreatedAt()
            .equals(other.getCreatedAt())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (37 * hash) + SCHEMA_FIELD_NUMBER;
      hash = (53 * hash) + getSchema().hashCode();
      if (getUsersCount() > 0) {
        hash = (37 * hash) + USERS_FIELD_NUMBER;
        hash = (53 * hash) + getUsersList().hashCode();
      }
      if (getUserGroupsCount() > 0) {
        hash = (37 * hash) + USER_GROUPS_FIELD_NUMBER;
        hash = (53 * hash) + getUserGroupsList().hashCode();
      }
      if (getItemsCount() > 0) {
        hash = (37 * hash) + ITEMS_FIELD_NUMBER;
        hash = (53 * hash) + getItemsList().hashCode();
      }
      if (getTagsCount() > 0) {
        hash = (37 * hash) + TAGS_FIELD_NUMBER;
        hash = (53 * hash) + getTagsList().hashCode();
      }
      hash = (37 * hash) + RAW_DATA_FIELD_NUMBER;
      hash = (53 * hash) + getRawData().hashCode();
      if (hasCreatedAt()) {
        hash = (37 * hash) + CREATED_AT_FIELD_NUMBER;
        hash = (53 * hash) + getCreatedAt().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.qtodo.socket.proto.SockMessage.MessageProto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qtodo.socket.proto.SockMessage.MessageProto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qtodo.socket.proto.SockMessage.MessageProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qtodo.socket.proto.SockMessage.MessageProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qtodo.socket.proto.SockMessage.MessageProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qtodo.socket.proto.SockMessage.MessageProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qtodo.socket.proto.SockMessage.MessageProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.qtodo.socket.proto.SockMessage.MessageProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.qtodo.socket.proto.SockMessage.MessageProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.qtodo.socket.proto.SockMessage.MessageProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.qtodo.socket.proto.SockMessage.MessageProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.qtodo.socket.proto.SockMessage.MessageProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.qtodo.socket.proto.SockMessage.MessageProto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MessageProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MessageProto)
        com.qtodo.socket.proto.SockMessage.MessageProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.qtodo.socket.proto.SockMessage.internal_static_MessageProto_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.qtodo.socket.proto.SockMessage.internal_static_MessageProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.qtodo.socket.proto.SockMessage.MessageProto.class, com.qtodo.socket.proto.SockMessage.MessageProto.Builder.class);
      }

      // Construct using com.qtodo.socket.proto.SockMessage.MessageProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          internalGetUsersFieldBuilder();
          internalGetItemsFieldBuilder();
          internalGetTagsFieldBuilder();
          internalGetCreatedAtFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        type_ = "";
        message_ = "";
        schema_ = "";
        if (usersBuilder_ == null) {
          users_ = java.util.Collections.emptyList();
        } else {
          users_ = null;
          usersBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        userGroups_ =
            com.google.protobuf.LazyStringArrayList.emptyList();
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
        } else {
          items_ = null;
          itemsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000020);
        if (tagsBuilder_ == null) {
          tags_ = java.util.Collections.emptyList();
        } else {
          tags_ = null;
          tagsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000040);
        rawData_ = com.google.protobuf.ByteString.EMPTY;
        createdAt_ = null;
        if (createdAtBuilder_ != null) {
          createdAtBuilder_.dispose();
          createdAtBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.qtodo.socket.proto.SockMessage.internal_static_MessageProto_descriptor;
      }

      @java.lang.Override
      public com.qtodo.socket.proto.SockMessage.MessageProto getDefaultInstanceForType() {
        return com.qtodo.socket.proto.SockMessage.MessageProto.getDefaultInstance();
      }

      @java.lang.Override
      public com.qtodo.socket.proto.SockMessage.MessageProto build() {
        com.qtodo.socket.proto.SockMessage.MessageProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.qtodo.socket.proto.SockMessage.MessageProto buildPartial() {
        com.qtodo.socket.proto.SockMessage.MessageProto result = new com.qtodo.socket.proto.SockMessage.MessageProto(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(com.qtodo.socket.proto.SockMessage.MessageProto result) {
        if (usersBuilder_ == null) {
          if (((bitField0_ & 0x00000008) != 0)) {
            users_ = java.util.Collections.unmodifiableList(users_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.users_ = users_;
        } else {
          result.users_ = usersBuilder_.build();
        }
        if (itemsBuilder_ == null) {
          if (((bitField0_ & 0x00000020) != 0)) {
            items_ = java.util.Collections.unmodifiableList(items_);
            bitField0_ = (bitField0_ & ~0x00000020);
          }
          result.items_ = items_;
        } else {
          result.items_ = itemsBuilder_.build();
        }
        if (tagsBuilder_ == null) {
          if (((bitField0_ & 0x00000040) != 0)) {
            tags_ = java.util.Collections.unmodifiableList(tags_);
            bitField0_ = (bitField0_ & ~0x00000040);
          }
          result.tags_ = tags_;
        } else {
          result.tags_ = tagsBuilder_.build();
        }
      }

      private void buildPartial0(com.qtodo.socket.proto.SockMessage.MessageProto result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.type_ = type_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.message_ = message_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.schema_ = schema_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          userGroups_.makeImmutable();
          result.userGroups_ = userGroups_;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.rawData_ = rawData_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.createdAt_ = createdAtBuilder_ == null
              ? createdAt_
              : createdAtBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.qtodo.socket.proto.SockMessage.MessageProto) {
          return mergeFrom((com.qtodo.socket.proto.SockMessage.MessageProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.qtodo.socket.proto.SockMessage.MessageProto other) {
        if (other == com.qtodo.socket.proto.SockMessage.MessageProto.getDefaultInstance()) return this;
        if (!other.getType().isEmpty()) {
          type_ = other.type_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getSchema().isEmpty()) {
          schema_ = other.schema_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (usersBuilder_ == null) {
          if (!other.users_.isEmpty()) {
            if (users_.isEmpty()) {
              users_ = other.users_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureUsersIsMutable();
              users_.addAll(other.users_);
            }
            onChanged();
          }
        } else {
          if (!other.users_.isEmpty()) {
            if (usersBuilder_.isEmpty()) {
              usersBuilder_.dispose();
              usersBuilder_ = null;
              users_ = other.users_;
              bitField0_ = (bitField0_ & ~0x00000008);
              usersBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   internalGetUsersFieldBuilder() : null;
            } else {
              usersBuilder_.addAllMessages(other.users_);
            }
          }
        }
        if (!other.userGroups_.isEmpty()) {
          if (userGroups_.isEmpty()) {
            userGroups_ = other.userGroups_;
            bitField0_ |= 0x00000010;
          } else {
            ensureUserGroupsIsMutable();
            userGroups_.addAll(other.userGroups_);
          }
          onChanged();
        }
        if (itemsBuilder_ == null) {
          if (!other.items_.isEmpty()) {
            if (items_.isEmpty()) {
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000020);
            } else {
              ensureItemsIsMutable();
              items_.addAll(other.items_);
            }
            onChanged();
          }
        } else {
          if (!other.items_.isEmpty()) {
            if (itemsBuilder_.isEmpty()) {
              itemsBuilder_.dispose();
              itemsBuilder_ = null;
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000020);
              itemsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   internalGetItemsFieldBuilder() : null;
            } else {
              itemsBuilder_.addAllMessages(other.items_);
            }
          }
        }
        if (tagsBuilder_ == null) {
          if (!other.tags_.isEmpty()) {
            if (tags_.isEmpty()) {
              tags_ = other.tags_;
              bitField0_ = (bitField0_ & ~0x00000040);
            } else {
              ensureTagsIsMutable();
              tags_.addAll(other.tags_);
            }
            onChanged();
          }
        } else {
          if (!other.tags_.isEmpty()) {
            if (tagsBuilder_.isEmpty()) {
              tagsBuilder_.dispose();
              tagsBuilder_ = null;
              tags_ = other.tags_;
              bitField0_ = (bitField0_ & ~0x00000040);
              tagsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   internalGetTagsFieldBuilder() : null;
            } else {
              tagsBuilder_.addAllMessages(other.tags_);
            }
          }
        }
        if (!other.getRawData().isEmpty()) {
          setRawData(other.getRawData());
        }
        if (other.hasCreatedAt()) {
          mergeCreatedAt(other.getCreatedAt());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                type_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                message_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                schema_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                com.qtodo.socket.proto.User.UserProto m =
                    input.readMessage(
                        com.qtodo.socket.proto.User.UserProto.parser(),
                        extensionRegistry);
                if (usersBuilder_ == null) {
                  ensureUsersIsMutable();
                  users_.add(m);
                } else {
                  usersBuilder_.addMessage(m);
                }
                break;
              } // case 34
              case 42: {
                java.lang.String s = input.readStringRequireUtf8();
                ensureUserGroupsIsMutable();
                userGroups_.add(s);
                break;
              } // case 42
              case 50: {
                com.qtodo.socket.proto.TodoItem.TodoItemProto m =
                    input.readMessage(
                        com.qtodo.socket.proto.TodoItem.TodoItemProto.parser(),
                        extensionRegistry);
                if (itemsBuilder_ == null) {
                  ensureItemsIsMutable();
                  items_.add(m);
                } else {
                  itemsBuilder_.addMessage(m);
                }
                break;
              } // case 50
              case 58: {
                com.qtodo.socket.proto.TodoItem.TagProto m =
                    input.readMessage(
                        com.qtodo.socket.proto.TodoItem.TagProto.parser(),
                        extensionRegistry);
                if (tagsBuilder_ == null) {
                  ensureTagsIsMutable();
                  tags_.add(m);
                } else {
                  tagsBuilder_.addMessage(m);
                }
                break;
              } // case 58
              case 66: {
                rawData_ = input.readBytes();
                bitField0_ |= 0x00000080;
                break;
              } // case 66
              case 74: {
                input.readMessage(
                    internalGetCreatedAtFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000100;
                break;
              } // case 74
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object type_ = "";
      /**
       * <code>string type = 1;</code>
       * @return The type.
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string type = 1;</code>
       * @return The bytes for type.
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        type_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        type_ = getDefaultInstance().getType();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string type = 1;</code>
       * @param value The bytes for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        type_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <code>string message = 2;</code>
       * @return The message.
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string message = 2;</code>
       * @return The bytes for message.
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string message = 2;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        message_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string message = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        message_ = getDefaultInstance().getMessage();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string message = 2;</code>
       * @param value The bytes for message to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        message_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object schema_ = "";
      /**
       * <code>string schema = 3;</code>
       * @return The schema.
       */
      public java.lang.String getSchema() {
        java.lang.Object ref = schema_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          schema_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string schema = 3;</code>
       * @return The bytes for schema.
       */
      public com.google.protobuf.ByteString
          getSchemaBytes() {
        java.lang.Object ref = schema_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          schema_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string schema = 3;</code>
       * @param value The schema to set.
       * @return This builder for chaining.
       */
      public Builder setSchema(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        schema_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string schema = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSchema() {
        schema_ = getDefaultInstance().getSchema();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string schema = 3;</code>
       * @param value The bytes for schema to set.
       * @return This builder for chaining.
       */
      public Builder setSchemaBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        schema_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.util.List<com.qtodo.socket.proto.User.UserProto> users_ =
        java.util.Collections.emptyList();
      private void ensureUsersIsMutable() {
        if (!((bitField0_ & 0x00000008) != 0)) {
          users_ = new java.util.ArrayList<com.qtodo.socket.proto.User.UserProto>(users_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.qtodo.socket.proto.User.UserProto, com.qtodo.socket.proto.User.UserProto.Builder, com.qtodo.socket.proto.User.UserProtoOrBuilder> usersBuilder_;

      /**
       * <code>repeated .UserProto users = 4;</code>
       */
      public java.util.List<com.qtodo.socket.proto.User.UserProto> getUsersList() {
        if (usersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(users_);
        } else {
          return usersBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .UserProto users = 4;</code>
       */
      public int getUsersCount() {
        if (usersBuilder_ == null) {
          return users_.size();
        } else {
          return usersBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .UserProto users = 4;</code>
       */
      public com.qtodo.socket.proto.User.UserProto getUsers(int index) {
        if (usersBuilder_ == null) {
          return users_.get(index);
        } else {
          return usersBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .UserProto users = 4;</code>
       */
      public Builder setUsers(
          int index, com.qtodo.socket.proto.User.UserProto value) {
        if (usersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUsersIsMutable();
          users_.set(index, value);
          onChanged();
        } else {
          usersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .UserProto users = 4;</code>
       */
      public Builder setUsers(
          int index, com.qtodo.socket.proto.User.UserProto.Builder builderForValue) {
        if (usersBuilder_ == null) {
          ensureUsersIsMutable();
          users_.set(index, builderForValue.build());
          onChanged();
        } else {
          usersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .UserProto users = 4;</code>
       */
      public Builder addUsers(com.qtodo.socket.proto.User.UserProto value) {
        if (usersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUsersIsMutable();
          users_.add(value);
          onChanged();
        } else {
          usersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .UserProto users = 4;</code>
       */
      public Builder addUsers(
          int index, com.qtodo.socket.proto.User.UserProto value) {
        if (usersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUsersIsMutable();
          users_.add(index, value);
          onChanged();
        } else {
          usersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .UserProto users = 4;</code>
       */
      public Builder addUsers(
          com.qtodo.socket.proto.User.UserProto.Builder builderForValue) {
        if (usersBuilder_ == null) {
          ensureUsersIsMutable();
          users_.add(builderForValue.build());
          onChanged();
        } else {
          usersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .UserProto users = 4;</code>
       */
      public Builder addUsers(
          int index, com.qtodo.socket.proto.User.UserProto.Builder builderForValue) {
        if (usersBuilder_ == null) {
          ensureUsersIsMutable();
          users_.add(index, builderForValue.build());
          onChanged();
        } else {
          usersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .UserProto users = 4;</code>
       */
      public Builder addAllUsers(
          java.lang.Iterable<? extends com.qtodo.socket.proto.User.UserProto> values) {
        if (usersBuilder_ == null) {
          ensureUsersIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, users_);
          onChanged();
        } else {
          usersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .UserProto users = 4;</code>
       */
      public Builder clearUsers() {
        if (usersBuilder_ == null) {
          users_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          usersBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .UserProto users = 4;</code>
       */
      public Builder removeUsers(int index) {
        if (usersBuilder_ == null) {
          ensureUsersIsMutable();
          users_.remove(index);
          onChanged();
        } else {
          usersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .UserProto users = 4;</code>
       */
      public com.qtodo.socket.proto.User.UserProto.Builder getUsersBuilder(
          int index) {
        return internalGetUsersFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .UserProto users = 4;</code>
       */
      public com.qtodo.socket.proto.User.UserProtoOrBuilder getUsersOrBuilder(
          int index) {
        if (usersBuilder_ == null) {
          return users_.get(index);  } else {
          return usersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .UserProto users = 4;</code>
       */
      public java.util.List<? extends com.qtodo.socket.proto.User.UserProtoOrBuilder> 
           getUsersOrBuilderList() {
        if (usersBuilder_ != null) {
          return usersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(users_);
        }
      }
      /**
       * <code>repeated .UserProto users = 4;</code>
       */
      public com.qtodo.socket.proto.User.UserProto.Builder addUsersBuilder() {
        return internalGetUsersFieldBuilder().addBuilder(
            com.qtodo.socket.proto.User.UserProto.getDefaultInstance());
      }
      /**
       * <code>repeated .UserProto users = 4;</code>
       */
      public com.qtodo.socket.proto.User.UserProto.Builder addUsersBuilder(
          int index) {
        return internalGetUsersFieldBuilder().addBuilder(
            index, com.qtodo.socket.proto.User.UserProto.getDefaultInstance());
      }
      /**
       * <code>repeated .UserProto users = 4;</code>
       */
      public java.util.List<com.qtodo.socket.proto.User.UserProto.Builder> 
           getUsersBuilderList() {
        return internalGetUsersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.qtodo.socket.proto.User.UserProto, com.qtodo.socket.proto.User.UserProto.Builder, com.qtodo.socket.proto.User.UserProtoOrBuilder> 
          internalGetUsersFieldBuilder() {
        if (usersBuilder_ == null) {
          usersBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.qtodo.socket.proto.User.UserProto, com.qtodo.socket.proto.User.UserProto.Builder, com.qtodo.socket.proto.User.UserProtoOrBuilder>(
                  users_,
                  ((bitField0_ & 0x00000008) != 0),
                  getParentForChildren(),
                  isClean());
          users_ = null;
        }
        return usersBuilder_;
      }

      private com.google.protobuf.LazyStringArrayList userGroups_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      private void ensureUserGroupsIsMutable() {
        if (!userGroups_.isModifiable()) {
          userGroups_ = new com.google.protobuf.LazyStringArrayList(userGroups_);
        }
        bitField0_ |= 0x00000010;
      }
      /**
       * <code>repeated string user_groups = 5;</code>
       * @return A list containing the userGroups.
       */
      public com.google.protobuf.ProtocolStringList
          getUserGroupsList() {
        userGroups_.makeImmutable();
        return userGroups_;
      }
      /**
       * <code>repeated string user_groups = 5;</code>
       * @return The count of userGroups.
       */
      public int getUserGroupsCount() {
        return userGroups_.size();
      }
      /**
       * <code>repeated string user_groups = 5;</code>
       * @param index The index of the element to return.
       * @return The userGroups at the given index.
       */
      public java.lang.String getUserGroups(int index) {
        return userGroups_.get(index);
      }
      /**
       * <code>repeated string user_groups = 5;</code>
       * @param index The index of the value to return.
       * @return The bytes of the userGroups at the given index.
       */
      public com.google.protobuf.ByteString
          getUserGroupsBytes(int index) {
        return userGroups_.getByteString(index);
      }
      /**
       * <code>repeated string user_groups = 5;</code>
       * @param index The index to set the value at.
       * @param value The userGroups to set.
       * @return This builder for chaining.
       */
      public Builder setUserGroups(
          int index, java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureUserGroupsIsMutable();
        userGroups_.set(index, value);
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string user_groups = 5;</code>
       * @param value The userGroups to add.
       * @return This builder for chaining.
       */
      public Builder addUserGroups(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureUserGroupsIsMutable();
        userGroups_.add(value);
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string user_groups = 5;</code>
       * @param values The userGroups to add.
       * @return This builder for chaining.
       */
      public Builder addAllUserGroups(
          java.lang.Iterable<java.lang.String> values) {
        ensureUserGroupsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, userGroups_);
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string user_groups = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserGroups() {
        userGroups_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string user_groups = 5;</code>
       * @param value The bytes of the userGroups to add.
       * @return This builder for chaining.
       */
      public Builder addUserGroupsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensureUserGroupsIsMutable();
        userGroups_.add(value);
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private java.util.List<com.qtodo.socket.proto.TodoItem.TodoItemProto> items_ =
        java.util.Collections.emptyList();
      private void ensureItemsIsMutable() {
        if (!((bitField0_ & 0x00000020) != 0)) {
          items_ = new java.util.ArrayList<com.qtodo.socket.proto.TodoItem.TodoItemProto>(items_);
          bitField0_ |= 0x00000020;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.qtodo.socket.proto.TodoItem.TodoItemProto, com.qtodo.socket.proto.TodoItem.TodoItemProto.Builder, com.qtodo.socket.proto.TodoItem.TodoItemProtoOrBuilder> itemsBuilder_;

      /**
       * <code>repeated .TodoItemProto items = 6;</code>
       */
      public java.util.List<com.qtodo.socket.proto.TodoItem.TodoItemProto> getItemsList() {
        if (itemsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(items_);
        } else {
          return itemsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .TodoItemProto items = 6;</code>
       */
      public int getItemsCount() {
        if (itemsBuilder_ == null) {
          return items_.size();
        } else {
          return itemsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .TodoItemProto items = 6;</code>
       */
      public com.qtodo.socket.proto.TodoItem.TodoItemProto getItems(int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);
        } else {
          return itemsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .TodoItemProto items = 6;</code>
       */
      public Builder setItems(
          int index, com.qtodo.socket.proto.TodoItem.TodoItemProto value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.set(index, value);
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .TodoItemProto items = 6;</code>
       */
      public Builder setItems(
          int index, com.qtodo.socket.proto.TodoItem.TodoItemProto.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.set(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .TodoItemProto items = 6;</code>
       */
      public Builder addItems(com.qtodo.socket.proto.TodoItem.TodoItemProto value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .TodoItemProto items = 6;</code>
       */
      public Builder addItems(
          int index, com.qtodo.socket.proto.TodoItem.TodoItemProto value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(index, value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .TodoItemProto items = 6;</code>
       */
      public Builder addItems(
          com.qtodo.socket.proto.TodoItem.TodoItemProto.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .TodoItemProto items = 6;</code>
       */
      public Builder addItems(
          int index, com.qtodo.socket.proto.TodoItem.TodoItemProto.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .TodoItemProto items = 6;</code>
       */
      public Builder addAllItems(
          java.lang.Iterable<? extends com.qtodo.socket.proto.TodoItem.TodoItemProto> values) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, items_);
          onChanged();
        } else {
          itemsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .TodoItemProto items = 6;</code>
       */
      public Builder clearItems() {
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
          onChanged();
        } else {
          itemsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .TodoItemProto items = 6;</code>
       */
      public Builder removeItems(int index) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.remove(index);
          onChanged();
        } else {
          itemsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .TodoItemProto items = 6;</code>
       */
      public com.qtodo.socket.proto.TodoItem.TodoItemProto.Builder getItemsBuilder(
          int index) {
        return internalGetItemsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .TodoItemProto items = 6;</code>
       */
      public com.qtodo.socket.proto.TodoItem.TodoItemProtoOrBuilder getItemsOrBuilder(
          int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);  } else {
          return itemsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .TodoItemProto items = 6;</code>
       */
      public java.util.List<? extends com.qtodo.socket.proto.TodoItem.TodoItemProtoOrBuilder> 
           getItemsOrBuilderList() {
        if (itemsBuilder_ != null) {
          return itemsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(items_);
        }
      }
      /**
       * <code>repeated .TodoItemProto items = 6;</code>
       */
      public com.qtodo.socket.proto.TodoItem.TodoItemProto.Builder addItemsBuilder() {
        return internalGetItemsFieldBuilder().addBuilder(
            com.qtodo.socket.proto.TodoItem.TodoItemProto.getDefaultInstance());
      }
      /**
       * <code>repeated .TodoItemProto items = 6;</code>
       */
      public com.qtodo.socket.proto.TodoItem.TodoItemProto.Builder addItemsBuilder(
          int index) {
        return internalGetItemsFieldBuilder().addBuilder(
            index, com.qtodo.socket.proto.TodoItem.TodoItemProto.getDefaultInstance());
      }
      /**
       * <code>repeated .TodoItemProto items = 6;</code>
       */
      public java.util.List<com.qtodo.socket.proto.TodoItem.TodoItemProto.Builder> 
           getItemsBuilderList() {
        return internalGetItemsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.qtodo.socket.proto.TodoItem.TodoItemProto, com.qtodo.socket.proto.TodoItem.TodoItemProto.Builder, com.qtodo.socket.proto.TodoItem.TodoItemProtoOrBuilder> 
          internalGetItemsFieldBuilder() {
        if (itemsBuilder_ == null) {
          itemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.qtodo.socket.proto.TodoItem.TodoItemProto, com.qtodo.socket.proto.TodoItem.TodoItemProto.Builder, com.qtodo.socket.proto.TodoItem.TodoItemProtoOrBuilder>(
                  items_,
                  ((bitField0_ & 0x00000020) != 0),
                  getParentForChildren(),
                  isClean());
          items_ = null;
        }
        return itemsBuilder_;
      }

      private java.util.List<com.qtodo.socket.proto.TodoItem.TagProto> tags_ =
        java.util.Collections.emptyList();
      private void ensureTagsIsMutable() {
        if (!((bitField0_ & 0x00000040) != 0)) {
          tags_ = new java.util.ArrayList<com.qtodo.socket.proto.TodoItem.TagProto>(tags_);
          bitField0_ |= 0x00000040;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.qtodo.socket.proto.TodoItem.TagProto, com.qtodo.socket.proto.TodoItem.TagProto.Builder, com.qtodo.socket.proto.TodoItem.TagProtoOrBuilder> tagsBuilder_;

      /**
       * <code>repeated .TagProto tags = 7;</code>
       */
      public java.util.List<com.qtodo.socket.proto.TodoItem.TagProto> getTagsList() {
        if (tagsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(tags_);
        } else {
          return tagsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .TagProto tags = 7;</code>
       */
      public int getTagsCount() {
        if (tagsBuilder_ == null) {
          return tags_.size();
        } else {
          return tagsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .TagProto tags = 7;</code>
       */
      public com.qtodo.socket.proto.TodoItem.TagProto getTags(int index) {
        if (tagsBuilder_ == null) {
          return tags_.get(index);
        } else {
          return tagsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .TagProto tags = 7;</code>
       */
      public Builder setTags(
          int index, com.qtodo.socket.proto.TodoItem.TagProto value) {
        if (tagsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTagsIsMutable();
          tags_.set(index, value);
          onChanged();
        } else {
          tagsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .TagProto tags = 7;</code>
       */
      public Builder setTags(
          int index, com.qtodo.socket.proto.TodoItem.TagProto.Builder builderForValue) {
        if (tagsBuilder_ == null) {
          ensureTagsIsMutable();
          tags_.set(index, builderForValue.build());
          onChanged();
        } else {
          tagsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .TagProto tags = 7;</code>
       */
      public Builder addTags(com.qtodo.socket.proto.TodoItem.TagProto value) {
        if (tagsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTagsIsMutable();
          tags_.add(value);
          onChanged();
        } else {
          tagsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .TagProto tags = 7;</code>
       */
      public Builder addTags(
          int index, com.qtodo.socket.proto.TodoItem.TagProto value) {
        if (tagsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTagsIsMutable();
          tags_.add(index, value);
          onChanged();
        } else {
          tagsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .TagProto tags = 7;</code>
       */
      public Builder addTags(
          com.qtodo.socket.proto.TodoItem.TagProto.Builder builderForValue) {
        if (tagsBuilder_ == null) {
          ensureTagsIsMutable();
          tags_.add(builderForValue.build());
          onChanged();
        } else {
          tagsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .TagProto tags = 7;</code>
       */
      public Builder addTags(
          int index, com.qtodo.socket.proto.TodoItem.TagProto.Builder builderForValue) {
        if (tagsBuilder_ == null) {
          ensureTagsIsMutable();
          tags_.add(index, builderForValue.build());
          onChanged();
        } else {
          tagsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .TagProto tags = 7;</code>
       */
      public Builder addAllTags(
          java.lang.Iterable<? extends com.qtodo.socket.proto.TodoItem.TagProto> values) {
        if (tagsBuilder_ == null) {
          ensureTagsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, tags_);
          onChanged();
        } else {
          tagsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .TagProto tags = 7;</code>
       */
      public Builder clearTags() {
        if (tagsBuilder_ == null) {
          tags_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000040);
          onChanged();
        } else {
          tagsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .TagProto tags = 7;</code>
       */
      public Builder removeTags(int index) {
        if (tagsBuilder_ == null) {
          ensureTagsIsMutable();
          tags_.remove(index);
          onChanged();
        } else {
          tagsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .TagProto tags = 7;</code>
       */
      public com.qtodo.socket.proto.TodoItem.TagProto.Builder getTagsBuilder(
          int index) {
        return internalGetTagsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .TagProto tags = 7;</code>
       */
      public com.qtodo.socket.proto.TodoItem.TagProtoOrBuilder getTagsOrBuilder(
          int index) {
        if (tagsBuilder_ == null) {
          return tags_.get(index);  } else {
          return tagsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .TagProto tags = 7;</code>
       */
      public java.util.List<? extends com.qtodo.socket.proto.TodoItem.TagProtoOrBuilder> 
           getTagsOrBuilderList() {
        if (tagsBuilder_ != null) {
          return tagsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(tags_);
        }
      }
      /**
       * <code>repeated .TagProto tags = 7;</code>
       */
      public com.qtodo.socket.proto.TodoItem.TagProto.Builder addTagsBuilder() {
        return internalGetTagsFieldBuilder().addBuilder(
            com.qtodo.socket.proto.TodoItem.TagProto.getDefaultInstance());
      }
      /**
       * <code>repeated .TagProto tags = 7;</code>
       */
      public com.qtodo.socket.proto.TodoItem.TagProto.Builder addTagsBuilder(
          int index) {
        return internalGetTagsFieldBuilder().addBuilder(
            index, com.qtodo.socket.proto.TodoItem.TagProto.getDefaultInstance());
      }
      /**
       * <code>repeated .TagProto tags = 7;</code>
       */
      public java.util.List<com.qtodo.socket.proto.TodoItem.TagProto.Builder> 
           getTagsBuilderList() {
        return internalGetTagsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.qtodo.socket.proto.TodoItem.TagProto, com.qtodo.socket.proto.TodoItem.TagProto.Builder, com.qtodo.socket.proto.TodoItem.TagProtoOrBuilder> 
          internalGetTagsFieldBuilder() {
        if (tagsBuilder_ == null) {
          tagsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.qtodo.socket.proto.TodoItem.TagProto, com.qtodo.socket.proto.TodoItem.TagProto.Builder, com.qtodo.socket.proto.TodoItem.TagProtoOrBuilder>(
                  tags_,
                  ((bitField0_ & 0x00000040) != 0),
                  getParentForChildren(),
                  isClean());
          tags_ = null;
        }
        return tagsBuilder_;
      }

      private com.google.protobuf.ByteString rawData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes raw_data = 8;</code>
       * @return The rawData.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getRawData() {
        return rawData_;
      }
      /**
       * <code>bytes raw_data = 8;</code>
       * @param value The rawData to set.
       * @return This builder for chaining.
       */
      public Builder setRawData(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        rawData_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>bytes raw_data = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearRawData() {
        bitField0_ = (bitField0_ & ~0x00000080);
        rawData_ = getDefaultInstance().getRawData();
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp createdAt_;
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> createdAtBuilder_;
      /**
       * <code>.google.protobuf.Timestamp created_at = 9;</code>
       * @return Whether the createdAt field is set.
       */
      public boolean hasCreatedAt() {
        return ((bitField0_ & 0x00000100) != 0);
      }
      /**
       * <code>.google.protobuf.Timestamp created_at = 9;</code>
       * @return The createdAt.
       */
      public com.google.protobuf.Timestamp getCreatedAt() {
        if (createdAtBuilder_ == null) {
          return createdAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
        } else {
          return createdAtBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp created_at = 9;</code>
       */
      public Builder setCreatedAt(com.google.protobuf.Timestamp value) {
        if (createdAtBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          createdAt_ = value;
        } else {
          createdAtBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp created_at = 9;</code>
       */
      public Builder setCreatedAt(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (createdAtBuilder_ == null) {
          createdAt_ = builderForValue.build();
        } else {
          createdAtBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp created_at = 9;</code>
       */
      public Builder mergeCreatedAt(com.google.protobuf.Timestamp value) {
        if (createdAtBuilder_ == null) {
          if (((bitField0_ & 0x00000100) != 0) &&
            createdAt_ != null &&
            createdAt_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
            getCreatedAtBuilder().mergeFrom(value);
          } else {
            createdAt_ = value;
          }
        } else {
          createdAtBuilder_.mergeFrom(value);
        }
        if (createdAt_ != null) {
          bitField0_ |= 0x00000100;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp created_at = 9;</code>
       */
      public Builder clearCreatedAt() {
        bitField0_ = (bitField0_ & ~0x00000100);
        createdAt_ = null;
        if (createdAtBuilder_ != null) {
          createdAtBuilder_.dispose();
          createdAtBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp created_at = 9;</code>
       */
      public com.google.protobuf.Timestamp.Builder getCreatedAtBuilder() {
        bitField0_ |= 0x00000100;
        onChanged();
        return internalGetCreatedAtFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp created_at = 9;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder() {
        if (createdAtBuilder_ != null) {
          return createdAtBuilder_.getMessageOrBuilder();
        } else {
          return createdAt_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp created_at = 9;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          internalGetCreatedAtFieldBuilder() {
        if (createdAtBuilder_ == null) {
          createdAtBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getCreatedAt(),
                  getParentForChildren(),
                  isClean());
          createdAt_ = null;
        }
        return createdAtBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:MessageProto)
    }

    // @@protoc_insertion_point(class_scope:MessageProto)
    private static final com.qtodo.socket.proto.SockMessage.MessageProto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.qtodo.socket.proto.SockMessage.MessageProto();
    }

    public static com.qtodo.socket.proto.SockMessage.MessageProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MessageProto>
        PARSER = new com.google.protobuf.AbstractParser<MessageProto>() {
      @java.lang.Override
      public MessageProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MessageProto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MessageProto> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.qtodo.socket.proto.SockMessage.MessageProto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MessageProto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MessageProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022sock_message.proto\032\037google/protobuf/ti" +
      "mestamp.proto\032\017todo_item.proto\032\nuser.pro" +
      "to\"\347\001\n\014MessageProto\022\014\n\004type\030\001 \001(\t\022\017\n\007mes" +
      "sage\030\002 \001(\t\022\016\n\006schema\030\003 \001(\t\022\031\n\005users\030\004 \003(" +
      "\0132\n.UserProto\022\023\n\013user_groups\030\005 \003(\t\022\035\n\005it" +
      "ems\030\006 \003(\0132\016.TodoItemProto\022\027\n\004tags\030\007 \003(\0132" +
      "\t.TagProto\022\020\n\010raw_data\030\010 \001(\014\022.\n\ncreated_" +
      "at\030\t \001(\0132\032.google.protobuf.TimestampB\030\n\026" +
      "com.qtodo.socket.protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.qtodo.socket.proto.TodoItem.getDescriptor(),
          com.qtodo.socket.proto.User.getDescriptor(),
        });
    internal_static_MessageProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MessageProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_MessageProto_descriptor,
        new java.lang.String[] { "Type", "Message", "Schema", "Users", "UserGroups", "Items", "Tags", "RawData", "CreatedAt", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.TimestampProto.getDescriptor();
    com.qtodo.socket.proto.TodoItem.getDescriptor();
    com.qtodo.socket.proto.User.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
